- hosts: web_nodes
  vars:
    os_packages:
      - python36
      - python36-pip
      - git
      - tree
      - mc
    bucket_name: "181356-kubala"
    python_dependencies:
      - boto3
      - pytest
      - flask
  tasks:
    - name: "Install os packages"
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ os_packages }}"
      become: yes
    - name: "Sync my repo"
      git:
        repo: https://bitbucket.org/jkanclerz/ani-creator.git
        dest: ~/ani-creator
    - name: "ensure env is configured"
      lineinfile:
        path: ~/.bashrc
        line: "export APP_BUCKET_NAME={{bucket_name}}"
    - raw: git config --global user.name "qubala"
    - raw: git config --global user.email "jq.kubala@gmail.com"
    - pip:
        name: "{{ item }}"
        executable: pip-3.6
      with_items: "{{ python_dependencies }}"
      become: yes
   
